### ISSUE TITLE
Double clicking on a file in webstorm doesn't take you to the file

### ISSUE THREAD

**Issue by jonathanleahy** [comod/git-scope#1]
Hi, I've been using git-scope for a long time. The latest version isn't behaving correctly in webstorm.
Once the git-scope window opens up you normally can double-click on a file and it'll open the source code. In the latest version of web storm this isn't happening.
Also the plugin has gone commercial, I've found this plug-in most useful, so getting that issue fixed by paying an annual fee sounds sensible to me.

**Comment by pvds** [comment]
@jonathanleahy what environment are you on?

Mine is:
- Apple Macbook M1 Pro (MacOS Ventura > 13.3 (22E252))
- WebStorm 2023.1 (#WS-231.8109.174 > latest version)
- Git Scope v3.0.6

**Comment by comod** [comment]
Planned to be fixed in the next Version

**Comment by comod** [comment]
update available https://plugins.jetbrains.com/plugin/10083-git-scope/versions/stable/350502
