### ISSUE TITLE
Branch selection menu pops up when tab is closed and entering vim insert mode

### ISSUE THREAD

**Issue by marthinwurer** [comod/git-scope#1]
I use the vim keybinding plugin. When I enter insert mode with `Shift-o`, the "Target branch in X" selection pops up. Hopefully this is an easy fix, because this is a useful plugin.

edit: just tried 2.1.1, that doesn't have the same issue, but is missing the newer functionality.

**Comment by comod** [comment]
Please check your Keymap. Search for "ToggleHead" and delete/reassign

**Comment by marthinwurer** [comment]
Funnily enough, I reinstalled the plugin to test this, but it works now even with the ToggleHead keybind assigned to the default value. I'll close this, but reopen it if it happens again.
