### ISSUE TITLE
A Bug was found that caused the prompt to be smaller in the position of the original line number

### ISSUE THREAD

**Issue by ZHOUXING1997** [comod/git-scope#10]
我遇到一个 Bug，在禁用/卸载插件后，行号位置的变更标识没了（ide自己的也没了）

提一个建议：能否可以将变更生成为 diff 文件

I encountered a Bug where after disabling/uninstalling the plugin, the change identifier for the line number location disappeared (and the ide's own disappeared).

Make a suggestion: Can you generate the changes as diff files

**Comment by comod** [comment]
I am not sure what do you mean.you may mean `Version Control > Confirmation > Highlight modified lines in the gutter`

**Comment by ZHOUXING1997** [comment]
Yes, I've been looking for this setup before.
Sorry for the previous interruption! I deleted some of my previous comments.


Is this setting of the editor turned off after installing this plug-in?


Can the diff of the plug-in be generated into a diff file that can be used by git?





周星
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "comod/git-scope"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年10月29日(星期天) 下午5:59
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [comod/git-scope] A Bug was found that caused the prompt to be smaller in the position of the original line number (Issue #10)





 
I am not sure what do you mean.you may mean Version Control &gt; Confirmation &gt; Highlight modified lines in the gutter
