### ISSUE TITLE
Can the ability to export differences as diff files be added?

### ISSUE THREAD

**Issue by ZHOUXING1997** [comod/git-scope#13]

**Comment by michaelwoelk** [comment]
To be honest, I don't understand what exactly you want. Currently, I do not plan to continue adding features, apart from this.

**Comment by comod** [comment]
To be honest, I don't understand what exactly you want. Currently, I do not plan to continue adding features, apart from this.

**Comment by RashiqAzhan** [comment]
![image](https://github.com/comod/git-scope/assets/7370540/82629b0f-239f-4348-9f64-17c64d4f5ad8)

Something like the option to select commits for each branch.

For example. If I'm working on the local `demo` branch and I make 3 commits. The way to get git scope to work is compare with origin `demo` branch. This no longer works after pushing though.

I would love to have the ability to individually select x commits from a certain branch to get the diff on the left gutter.
Something like ~3 from head while I'm working on local `demo` branch. After 2 more commits, ~5 head and so on.

**Comment by comod** [comment]
In the current Version i added Gut Scope to the VcsContextMenu. This allows to compare any commit with Git Scope. Maybe this helps

**Comment by RashiqAzhan** [comment]
Thank you. Can you share how to get the update and maybe some instructions if it's not apparent?

**Comment by ZHOUXING1997** [comment]
![image](https://github.com/comod/git-scope/assets/33240857/014579ad-33a2-44f3-9906-fc1e753c5344)
This is the feature I want.

Sorry, I didn't have time to reply before

**Comment by comod** [comment]
Maybe just use the console in this case? 
`git diff main..HEAD > changes.patch`
