### ISSUE TITLE
Branch selection dropdown appears at random times

### ISSUE THREAD

**Issue by hoxi** [comod/git-scope#3]
The branch selection dropdown appears at random times, often when the main window looses focus. This is seen on on a CLion in Linux, I don't seem to notice the same thing when using CLion on Windows.

Any timeline when an updated paid version can be available?

**Comment by comod** [comment]
Planned to be fixed in the next Version. Soon! I am 80% done with the rewrite.

**Comment by comod** [comment]
update available https://plugins.jetbrains.com/plugin/10083-git-scope/versions/stable/350502
